use_frameworks!

target 'SMSlideTransition_Example' do
  pod 'SMSlideTransition', :path => '/Users/user/Documents/MyPods/SMSlideTransition'

  target 'SMSlideTransition_Tests' do
    inherit! :search_paths

    
  end
end
